# Generated by Django 3.0 on 2022-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/noimage.jpg', upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
