# Generated by Django 3.0 on 2022-11-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20221120_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name=models.ImageField(blank=True, upload_to='productos')),
        ),
    ]
