# Generated by Django 3.0 on 2022-11-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20221120_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default='productos/noimage.jpg', on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/noimage.jpg', upload_to='productos', verbose_name='Imagen'),
        ),
    ]
