# Generated by Django 3.0 on 2022-11-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20221120_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/noimage.jpg', upload_to='media/', verbose_name='Imagen'),
        ),
    ]
