# Generated by Django 3.0 on 2022-11-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20221120_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
    ]
