# Generated by Django 3.0 on 2022-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_alter_categoria_id_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
