# Generated by Django 3.0 on 2022-12-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_auto_20221128_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='departamento',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='producto.Departamento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='producto.Fabricante'),
        ),
    ]
