version: '3.9'

services:
  django:
    build: .
    ports:
      - 8001:8001
    volumes:
      - .:/PGPI
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=acmecycling
      - POSTGRES_PASSWORD=acmecycling
      - POSTGRES_DB=acmecycling