# Generated by Django 3.0 on 2022-11-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalizarCompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ('-creacion',)},
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='dir',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='venta',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodoPago',
            field=models.CharField(choices=[('CR', 'Contrareembolso'), ('TJ', 'Tarjeta')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='venta',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
