# Generated by Django 3.0 on 2022-11-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalizarCompra', '0002_auto_20221128_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodoEnvio',
            field=models.CharField(choices=[('CO', 'Correo'), ('SE', 'Seur')], default='CO', max_length=2),
        ),
    ]
