# Generated by Django 3.0 on 2022-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalizarCompra', '0003_venta_metodoenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Transito', 'Transito'), ('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Recibido', 'Recibido')], default='Pendiente', max_length=100),
        ),
    ]
