# Generated by Django 3.0 on 2022-12-03 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalizarCompra', '0004_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Transito', 'Transito'), ('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Recibido', 'Recibido')], default='Pendiente', max_length=1200),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguimiento_id', models.CharField(max_length=70)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalizarCompra.Venta')),
            ],
        ),
    ]
