# Generated by Django 3.0 on 2022-12-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20221202_1714'),
        ('finalizarCompra', '0005_auto_20221203_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='cantidadVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalizarCompra.Venta')),
            ],
        ),
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
